### PR TITLE
added PMD PicoFlexx / libroyale support

### PR DESCRIPTION
**Pull request by akosmaroy**
changes add support for the PMD CamBoard PicoFlexx, see also ticket: https://github.com/victorprad/InfiniTAM/issues/57

### CODE REVIEW

**Comment by victorprad** [comment]
Nice job! It works much better than my version. I suspect it's because I wasn't using the proper calibration.

I will merge the PR soon.

**Comment by akosmaroy** [comment]
tnx. please make sure to include the latest commit as well, which sets a more generic use case: https://github.com/akosmaroy/InfiniTAM/commit/6dad94dfc647b6e1aa04d52edb61c11fb9e0eaca

two more notes:
- I didn't know how to set the 'scale' of depth. currently the depth is supplied ti InfitiTAM in millimeters
- there is an #ifdef part which allows for sending over the grayscale image to InfitiTAM. define PROVIDE_RGB for this to work. my experience was that this actually reduced the quality of the 3D model built

**Comment by victorprad** [comment]
i will merge with the latest commit as well. I will also do two other changes:
- my machine needed a 1s sleep after you start capture to make sure data is populated and you get valid sizes for infinitam.
- i will change it in the cmake so it's compile WITH royale, not without. most people won't have one of these cameras right now.

**Comment by akosmaroy** [comment]
\o/

**Pull request merged**
